# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 09:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NonBlockingLock',
            fields=[
                ('locked_object', models.CharField(max_length=150, unique=True, verbose_name='locked object')),
                ('created_on', models.DateTimeField(db_index=True, verbose_name='created on')),
                ('max_age', models.PositiveIntegerField(default=0, help_text='The age of a lock before it can be overwritten. 0 means indefinitely.', verbose_name='Maximum lock age')),
                ('expires_on', models.DateTimeField(db_index=True, default=datetime.datetime(2015, 9, 7, 3, 32, 8, 543000), verbose_name='expires on')),
                ('renewed_on', models.DateTimeField(db_index=True, default=datetime.datetime(2015, 9, 7, 3, 32, 18, 56000), verbose_name='renewed on')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'NonBlockingLocks',
                'verbose_name': 'NonBlockingLock',
                'ordering': ['created_on'],
            },
        ),
    ]
