# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 09:42
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locking', '0003_optimize_queries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonblockinglock',
            name='max_age',
            field=models.PositiveIntegerField(default=600, help_text='The age of a lock before it can be overwritten. 0 means indefinitely.', verbose_name='Maximum lock age'),
        ),
    ]
