# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 10:24
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locking', '0004_auto_20160907_0942'),
        ('locking', '0004_auto_20151115_0703'),
    ]

    operations = [
    ]
