# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locking', '0006_auto_20170609_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonblockinglock',
            name='locked_object',
            field=models.CharField(max_length=150, unique=True, verbose_name='locked object'),
        ),
    ]
